export const theme = {
  COLORS: {
    PRIMARY: '#D8754F',
    SECONDARY: '#FBA17F',
    TERTIARY: '#FFC2AC',
    SUCCESS: '#18A33E',
    ERROR: '#DC1B21',
    WHITE: '#FFF6EA',
    BLACK: '#565656',
    YELLOW: '#FFDCAC',
    SKELETTON: '#6F6F6F',
  },
  CARDS: {
    WHITE: '#FFFCEE',
    BLUE: '#95BFFF',
    BLACK: '#8F8F8F',
    RED: '#FF7A7A',
    GREEN: '#A3FFBC',
    COLORLESS: '#ABABAB',
  },
  SHADOW: {
    PRIMARY: '#D8754FEC',
    SECONDARY: '#FBA17FEC',
    TERTIARY: '#FFC2ACEC',
    SUCCESS: '#18A33EEC',
    ERROR: '#DC1B21EC',
    WHITE: '#FFF6EAEC',
    BLACK: '#565656EC',
    YELLOW: '#FFDCACEC',
  },
  TEXT_SIZE: {
    XS: '14px',
    SM: '16px',
    MD: '22px',
    XL: '26px',
    '2XL': '34px',
    '4XL': '40px',
  },
  NUMBER_SIZE: {
    XS: '16px',
    SM: '18px',
    MD: '26px',
    XL: '36px',
    DICE: '50px',
    PL: '160px',
  },
}