export const theme = {
  COLORS: {
    PRIMARY: '#D8754F',
    SECONDARY: '#FBA17F',
    TERTIARY: '#FFC2AC',
    SUCCESS: '#18A33E',
    ERROR: '#DC1B21',
    WHITE: '#FFF6EA',
    BLACK: '#565656',
    YELLOW: '#FFDCAC',
    SKELETTON: '#6F6F6F',
  },
  CARDS: {
    WHITE: '#FFFCEE',
    BLUE: '#95BFFF',
    BLACK: '#8F8F8F',
    RED: '#FF7A7A',
    GREEN: '#A3FFBC',
    COLORLESS: '#ABABAB',
  },
  SHADOW: {
    PRIMARY: '#D8754FEC',
    SECONDARY: '#FBA17FEC',
    TERTIARY: '#FFC2ACEC',
    SUCCESS: '#18A33EEC',
    ERROR: '#DC1B21EC',
    WHITE: '#FFF6EAEC',
    BLACK: '#565656EC',
    YELLOW: '#FFDCACEC',
  },
  TEXT_SIZE: {
    XS: '1rem',
    SM: '1.14rem',
    MD: '1.57rem',
    XL: '1.87rem',
    '2XL': '2.42rem',
    '4XL': '2.85',
  },
  NUMBER_SIZE: {
    XS: '1.14rem',
    SM: '1.28rem',
    MD: '1.87rem',
    XL: '2.57rem',
    DICE: '3.57rem',
    PL: '11rem',
  },
}